name: release-for-ubuntu
on: 
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
      - name: Update System
        run: sudo apt-get update --fix-missing -y
        
      - name: Install Environment
        run: sudo apt-get install gcc g++ libgl1-mesa-dev make wget -y
      
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.11.1
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          version: 5.12.10
          target: desktop
          modules: qtcharts
      
      - name: Pull Repositories
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build Project
        run: |
          qmake
          make
          ls -l

      - name: Gets latest created release info
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.DAILYBUILDING }}
      
      - name: Deploy
        env:
          outputdir: QtGitHubActionDemo-${{ steps.latest_release_info.outputs.tag_name }}-for-linux-x64
        run: |
          mkdir ${{ env.outputdir }}
          cp QtGitHubActionDemo ${{ env.outputdir }}
          wget https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage -o linuxdeployqt
          ./linuxdeployqt ${{ env.outputdir }}/QtGitHubActionDemo -appimage
          tar -zcvf ${{ env.outputdir }}.tar.gz ${{ env.outputdir }}
          ls -l
        
